In [14]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [15]:
df = pd.read_csv('all_props_new.csv')

In [16]:
df['results_per_total'] = df['results_per_total'] * 27.2114 / 1000

In [17]:
df

,Symbol,AtomicMass,AtomicRadius,Electronegativity,IonizationEnergy,ElectronAffinity,Polarizability,results_per_total,results_per_cation,CationSites,CounterIonSites,results_per_counter_ion,res_per_volm_per_site,Result,SpaceGroup,SpaceGroupNumber,Total Sites,Volume,mid,Reduced Formula
0,Ag,107.86800,172,1.93,7.576,1.302,55.00,0.260382,12.758459,0.750000,0.250000,0.038275,0.000485,0.484631,P6_3/mmc,194,8,157.956630,864952,Mg3Ag
1,Tm,168.93422,227,1.25,6.184,NaN,144.00,0.415654,20.366643,0.750000,0.750000,0.020367,0.000644,0.643827,Fm-3m,225,4,94.901190,1187610,TmMg3
2,Se,78.97000,190,2.55,9.752,2.021,28.90,0.135555,9.963117,0.500000,0.500000,0.009963,0.000244,0.243838,Fm-3m,225,2,40.859567,10760,MgSe
3,Yb,173.05000,242,NaN,6.254,NaN,139.00,0.637316,70.262715,0.333333,0.333333,0.070263,0.000852,0.851828,I4/mmm,139,6,164.969234,3217237,Yb2Mg
4,Ag,107.86800,172,1.93,7.576,1.302,55.00,0.263617,29.063243,0.333333,0.666667,0.014532,0.000528,0.527998,C2/m,12,6,110.088475,1185840,MgAg2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
410,Er,167.26000,235,1.24,6.108,NaN,150.00,0.689076,75.969200,0.333333,0.333333,0.075969,0.000896,0.896385,I4/mmm,139,3,84.750635,13497,Er2Mg
411,Ag,107.86800,172,1.93,7.576,1.302,55.00,0.259034,57.115951,0.166667,0.833333,0.011423,0.000546,0.545924,R32,155,6,104.622491,1185839,MgAg5
412,Bi,208.98040,207,2.02,7.289,0.946,53.00,0.181418,11.111640,0.600000,0.400000,0.016667,0.000238,0.237674,P-3m1,164,5,140.254610,569018,Mg3Bi2
413,Pd,106.42000,202,2.20,8.337,0.557,26.14,0.199488,43.986176,0.166667,0.833333,0.008797,0.000483,0.483304,R32,155,6,91.011368,976976,MgPd5
414,Sc,44.95591,211,1.36,6.561,0.188,97.00,0.384035,18.817362,0.750000,0.250000,0.056452,0.000624,0.623873,P6_3/mmc,194,8,180.973008,864937,Mg3Sc

In [18]:
element = 'Al'

In [19]:
grouped_df = df.groupby('Symbol')
oxy_group = pd.DataFrame()
for symbol, group in grouped_df:
    # print(f"Category: {symbol}")
    # print(group['Result'].max())
    # print(group['Result'].min())
    if symbol == element:
        # print(group['Result'])
        # print('---------------------')
        # print((group['Result'].max() - group['Result'].min())/group['Result'].mean() * 100)
        # print(group)
        oxy_group  = group
    # if(symbol == 'Al'):
    #     print(group)
    # print("\n")

oxy_group

,Symbol,AtomicMass,AtomicRadius,Electronegativity,IonizationEnergy,ElectronAffinity,Polarizability,results_per_total,results_per_cation,CationSites,CounterIonSites,results_per_counter_ion,res_per_volm_per_site,Result,SpaceGroup,SpaceGroupNumber,Total Sites,Volume,mid,Reduced Formula
75,Al,26.981538,184,1.61,5.986,0.441,57.8,0.305094,20.321730,0.551724,0.448276,0.025011,0.000563,0.562648,Cm,8,29,577.887881,1094685,Mg16Al13
107,Al,26.981538,184,1.61,5.986,0.441,57.8,0.324209,27.455060,0.433962,0.566038,0.021049,0.000617,0.616991,R-3,148,53,1023.461994,17659,Mg23Al30
306,Al,26.981538,184,1.61,5.986,0.441,57.8,0.294404,18.456186,0.586207,0.413793,0.026146,0.000552,0.552027,I-43m,217,29,568.369003,2151,Mg17Al12
330,Al,26.981538,184,1.61,5.986,0.441,57.8,0.222613,24.542594,0.333333,0.666667,0.012271,0.000446,0.446156,P6_3/mmc,194,12,220.036058,1094116,MgAl2
361,Al,26.981538,184,1.61,5.986,0.441,57.8,0.306598,20.421888,0.551724,0.448276,0.025135,0.000567,0.567256,R3m,160,29,576.019146,1094692,Mg16Al13

In [20]:
res = pd.read_csv('analysis_results.csv')

In [21]:
res = res[res['Symbol'] == element]

res

,Symbol,Structure,Total Sites,Cation Sites,Counter Ion Sites,Diff Energy,Diff per Total Sites,Diff per Cation Sites,Diff per Counter Ion Sites,Volume,mid,Composition
75,Al,Mg16 Al13,29,16.0,13.0,0.325148,0.011212,0.020322,0.025011,577.887881,1094685,Mg16 Al13
107,Al,Mg23 Al30,53,23.0,30.0,0.631466,0.011914,0.027455,0.021049,1023.461994,17659,Mg23 Al30
306,Al,Mg17 Al12,29,17.0,12.0,0.313755,0.010819,0.018456,0.026146,568.369003,2151,Mg17 Al12
330,Al,Mg4 Al8,12,4.0,8.0,0.098170,0.008181,0.024543,0.012271,220.036058,1094116,Mg4 Al8
361,Al,Mg16 Al13,29,16.0,13.0,0.326750,0.011267,0.020422,0.025135,576.019146,1094692,Mg16 Al13

In [22]:
oxy_group

,Symbol,AtomicMass,AtomicRadius,Electronegativity,IonizationEnergy,ElectronAffinity,Polarizability,results_per_total,results_per_cation,CationSites,CounterIonSites,results_per_counter_ion,res_per_volm_per_site,Result,SpaceGroup,SpaceGroupNumber,Total Sites,Volume,mid,Reduced Formula
75,Al,26.981538,184,1.61,5.986,0.441,57.8,0.305094,20.321730,0.551724,0.448276,0.025011,0.000563,0.562648,Cm,8,29,577.887881,1094685,Mg16Al13
107,Al,26.981538,184,1.61,5.986,0.441,57.8,0.324209,27.455060,0.433962,0.566038,0.021049,0.000617,0.616991,R-3,148,53,1023.461994,17659,Mg23Al30
306,Al,26.981538,184,1.61,5.986,0.441,57.8,0.294404,18.456186,0.586207,0.413793,0.026146,0.000552,0.552027,I-43m,217,29,568.369003,2151,Mg17Al12
330,Al,26.981538,184,1.61,5.986,0.441,57.8,0.222613,24.542594,0.333333,0.666667,0.012271,0.000446,0.446156,P6_3/mmc,194,12,220.036058,1094116,MgAl2
361,Al,26.981538,184,1.61,5.986,0.441,57.8,0.306598,20.421888,0.551724,0.448276,0.025135,0.000567,0.567256,R3m,160,29,576.019146,1094692,Mg16Al13

In [23]:
# oxy_group = oxy_group.sample(frac=0.5, random_state=42)

In [24]:
merged_df = pd.merge(res, oxy_group, left_index=True, right_index=True)
# merged_df.sort_values(by='Result',inplace=True, ascending=False)
# merged_df['SpaceGroup']

merged_df['Counter Ion Sites']

75     13.0
107    30.0
306    12.0
330     8.0
361    13.0
Name: Counter Ion Sites, dtype: float64

In [25]:
merged_df.rename(columns={"results_per_total": "Result_1"}, inplace=True)
# merged_df['Total Sites_x']

In [26]:
merged_df.sort_values(by='Result_1',inplace=True, ascending=True)

In [27]:
symbol = merged_df['Symbol_x'].values[0]
symbol

'Al'

In [29]:
# 1. Build a display label with subscripted CN
def make_disp_label(sg):
    # sg is like "Li-N0.33" or "K-N1.0"
    metal, cn_str = sg.split(f'-{element}')  # ["Li", "0.33"]
    cn_str = f"{float(cn_str):.2f}"  # Ensure two decimal places
    return rf"{cn_str}"

merged_df['DispLabel'] = merged_df['Structure_SG'].apply(make_disp_label)

# 2. Plot
x = np.arange(len(merged_df))
values = merged_df['Result_1']
labels = merged_df['DispLabel']

plt.figure(figsize=(16, 12))
plt.rcParams['font.family'] = 'Arial'
plt.bar(x, values, width=0.6, color='teal')

# 3. Use the LaTeX labels and set y-axis limit
plt.xticks(x, labels, rotation=45, ha='right', fontsize=38)
plt.yticks(fontsize=38)
plt.ylim(0, 0.4)  # Set y-axis limit to 0.5
plt.ylabel('Energy (eV)', fontsize=38)
plt.xlabel(rf'$\mathrm{{Mg{symbol}_X}}$', fontsize=38)

plt.tight_layout()
# plt.savefig(f'chemical_space/Cu_{symbol}_compounds.png', dpi=300, bbox_inches='tight')
plt.show()

KeyError: 'Structure_SG'